sudo: required
dist: xenial

language: node_js
node_js: 14

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=stable
  - HAXE_VERSION=nightly

install:
  - npm i lix@15.10.1 -g
  - lix download

script:
  - lix travix interp
  - lix travix neko
  - lix travix node
  - lix travix python
  - lix travix java
